<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.biel.lifecamp</groupId>
    <artifactId>services</artifactId>
    <version>0.1.0-SNAPSHOT</version>
  </parent>
  <artifactId>system-service</artifactId>
  <name>system-service</name>
  <dependencies>
    <dependency>
      <groupId>org.springframework.security</groupId>
      <artifactId>spring-security-crypto</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.security</groupId>
      <artifactId>spring-security-oauth2-jose</artifactId>
    </dependency>
  </dependencies>
</project>
